<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('cities')->insert([
    		['id' => '1', 'city' => 'Abriaquí','department_id' => '5'],
    		['id' => '2', 'city' => 'Acacías','department_id' => '50'],
    		['id' => '3', 'city' => 'Acandí','department_id' => '27'],
    		['id' => '4', 'city' => 'Acevedo','department_id' => '41'],
    		['id' => '5', 'city' => 'Achí','department_id' => '13'],
    		['id' => '6', 'city' => 'Agrado','department_id' => '41'],
    		['id' => '7', 'city' => 'Agua de Dios','department_id' => '25'],
    		['id' => '8', 'city' => 'Aguachica','department_id' => '20'],
    		['id' => '9', 'city' => 'Aguada','department_id' => '68'],
    		['id' => '10', 'city' => 'Aguadas','department_id' => '17'],
    		['id' => '11', 'city' => 'Aguazul','department_id' => '85'],
    		['id' => '12', 'city' => 'Agustín Codazzi','department_id' => '20'],
    		['id' => '13', 'city' => 'Aipe','department_id' => '41'],
    		['id' => '14', 'city' => 'Albania','department_id' => '18'],
    		['id' => '15', 'city' => 'Albania','department_id' => '44'],
    		['id' => '16', 'city' => 'Albania','department_id' => '68'],
    		['id' => '17', 'city' => 'Albán','department_id' => '25'],
    		['id' => '18', 'city' => 'Albán (San José)','department_id' => '52'],
    		['id' => '19', 'city' => 'Alcalá','department_id' => '76'],
    		['id' => '20', 'city' => 'Alejandria','department_id' => '5'],
    		['id' => '21', 'city' => 'Algarrobo','department_id' => '47'],
    		['id' => '22', 'city' => 'Algeciras','department_id' => '41'],
    		['id' => '23', 'city' => 'Almaguer','department_id' => '19'],
    		['id' => '24', 'city' => 'Almeida','department_id' => '15'],
    		['id' => '25', 'city' => 'Alpujarra','department_id' => '73'],
    		['id' => '26', 'city' => 'Altamira','department_id' => '41'],
    		['id' => '27', 'city' => 'Alto Baudó (Pie de Pato)','department_id' => '27'],
    		['id' => '28', 'city' => 'Altos del Rosario','department_id' => '13'],
    		['id' => '29', 'city' => 'Alvarado','department_id' => '73'],
    		['id' => '30', 'city' => 'Amagá','department_id' => '5'],
    		['id' => '31', 'city' => 'Amalfi','department_id' => '5'],
    		['id' => '32', 'city' => 'Ambalema','department_id' => '73'],
    		['id' => '33', 'city' => 'Anapoima','department_id' => '25'],
    		['id' => '34', 'city' => 'Ancuya','department_id' => '52'],
    		['id' => '35', 'city' => 'Andalucía','department_id' => '76'],
    		['id' => '36', 'city' => 'Andes','department_id' => '5'],
    		['id' => '37', 'city' => 'Angelópolis','department_id' => '5'],
    		['id' => '38', 'city' => 'Angostura','department_id' => '5'],
    		['id' => '39', 'city' => 'Anolaima','department_id' => '25'],
    		['id' => '40', 'city' => 'Anorí','department_id' => '5'],
    		['id' => '41', 'city' => 'Anserma','department_id' => '17'],
    		['id' => '42', 'city' => 'Ansermanuevo','department_id' => '76'],
    		['id' => '43', 'city' => 'Anzoátegui','department_id' => '73'],
    		['id' => '44', 'city' => 'Anzá','department_id' => '5'],
    		['id' => '45', 'city' => 'Apartadó','department_id' => '5'],
    		['id' => '46', 'city' => 'Apulo','department_id' => '25'],
    		['id' => '47', 'city' => 'Apía','department_id' => '66'],
    		['id' => '48', 'city' => 'Aquitania','department_id' => '15'],
    		['id' => '49', 'city' => 'Aracataca','department_id' => '47'],
    		['id' => '50', 'city' => 'Aranzazu','department_id' => '17'],
    		['id' => '51', 'city' => 'Aratoca','department_id' => '68'],
    		['id' => '52', 'city' => 'Arauca','department_id' => '81'],
    		['id' => '53', 'city' => 'Arauquita','department_id' => '81'],
    		['id' => '54', 'city' => 'Arbeláez','department_id' => '25'],
    		['id' => '55', 'city' => 'Arboleda (Berruecos)','department_id' => '52'],
    		['id' => '56', 'city' => 'Arboledas','department_id' => '54'],
    		['id' => '57', 'city' => 'Arboletes','department_id' => '5'],
    		['id' => '58', 'city' => 'Arcabuco','department_id' => '15'],
    		['id' => '59', 'city' => 'Arenal','department_id' => '13'],
    		['id' => '60', 'city' => 'Argelia','department_id' => '5'],
    		['id' => '61', 'city' => 'Argelia','department_id' => '19'],
    		['id' => '62', 'city' => 'Argelia','department_id' => '76'],
    		['id' => '63', 'city' => 'Ariguaní (El Difícil)','department_id' => '47'],
    		['id' => '64', 'city' => 'Arjona','department_id' => '13'],
    		['id' => '65', 'city' => 'Armenia','department_id' => '5'],
    		['id' => '66', 'city' => 'Armenia','department_id' => '63'],
    		['id' => '67', 'city' => 'Armero (Guayabal)','department_id' => '73'],
    		['id' => '68', 'city' => 'Arroyohondo','department_id' => '13'],
    		['id' => '69', 'city' => 'Astrea','department_id' => '20'],
    		['id' => '70', 'city' => 'Ataco','department_id' => '73'],
    		['id' => '71', 'city' => 'Atrato (Yuto)','department_id' => '27'],
    		['id' => '72', 'city' => 'Ayapel','department_id' => '23'],
    		['id' => '73', 'city' => 'Bagadó','department_id' => '27'],
    		['id' => '74', 'city' => 'Bahía Solano (Mútis)','department_id' => '27'],
    		['id' => '75', 'city' => 'Bajo Baudó (Pizarro)','department_id' => '27'],
    		['id' => '76', 'city' => 'Balboa','department_id' => '19'],
    		['id' => '77', 'city' => 'Balboa','department_id' => '66'],
    		['id' => '78', 'city' => 'Baranoa','department_id' => '8'],
    		['id' => '79', 'city' => 'Baraya','department_id' => '41'],
    		['id' => '80', 'city' => 'Barbacoas','department_id' => '52'],
    		['id' => '81', 'city' => 'Barbosa','department_id' => '5'],
    		['id' => '82', 'city' => 'Barbosa','department_id' => '68'],
    		['id' => '83', 'city' => 'Barichara','department_id' => '68'],
    		['id' => '84', 'city' => 'Barranca de Upía','department_id' => '50'],
    		['id' => '85', 'city' => 'Barrancabermeja','department_id' => '68'],
    		['id' => '86', 'city' => 'Barrancas','department_id' => '44'],
    		['id' => '87', 'city' => 'Barranco de Loba','department_id' => '13'],
    		['id' => '88', 'city' => 'Barranquilla','department_id' => '8'],
    		['id' => '89', 'city' => 'Becerríl','department_id' => '20'],
    		['id' => '90', 'city' => 'Belalcázar','department_id' => '17'],
    		['id' => '91', 'city' => 'Bello','department_id' => '5'],
    		['id' => '92', 'city' => 'Belmira','department_id' => '5'],
    		['id' => '93', 'city' => 'Beltrán','department_id' => '25'],
    		['id' => '94', 'city' => 'Belén','department_id' => '15'],
    		['id' => '95', 'city' => 'Belén','department_id' => '52'],
    		['id' => '96', 'city' => 'Belén de Bajirá','department_id' => '27'],
    		['id' => '97', 'city' => 'Belén de Umbría','department_id' => '66'],
    		['id' => '98', 'city' => 'Belén de los Andaquíes','department_id' => '18'],
    		['id' => '99', 'city' => 'Berbeo','department_id' => '15'],
    		['id' => '100', 'city' => 'Betania','department_id' => '5'],
    		['id' => '101', 'city' => 'Beteitiva','department_id' => '15'],
    		['id' => '102', 'city' => 'Betulia','department_id' => '5'],
    		['id' => '103', 'city' => 'Betulia','department_id' => '68'],
    		['id' => '104', 'city' => 'Bituima','department_id' => '25'],
    		['id' => '105', 'city' => 'Boavita','department_id' => '15'],
    		['id' => '106', 'city' => 'Bochalema','department_id' => '54'],
    		['id' => '107', 'city' => 'Bogotá D.C.','department_id' => '11'],
    		['id' => '108', 'city' => 'Bojacá','department_id' => '25'],
    		['id' => '109', 'city' => 'Bojayá (Bellavista)','department_id' => '27'],
    		['id' => '110', 'city' => 'Bolívar','department_id' => '5'],
    		['id' => '111', 'city' => 'Bolívar','department_id' => '19'],
    		['id' => '112', 'city' => 'Bolívar','department_id' => '68'],
    		['id' => '113', 'city' => 'Bolívar','department_id' => '76'],
    		['id' => '114', 'city' => 'Bosconia','department_id' => '20'],
    		['id' => '115', 'city' => 'Boyacá','department_id' => '15'],
    		['id' => '116', 'city' => 'Briceño','department_id' => '5'],
    		['id' => '117', 'city' => 'Briceño','department_id' => '15'],
    		['id' => '118', 'city' => 'Bucaramanga','department_id' => '68'],
    		['id' => '119', 'city' => 'Bucarasica','department_id' => '54'],
    		['id' => '120', 'city' => 'Buenaventura','department_id' => '76'],
    		['id' => '121', 'city' => 'Buenavista','department_id' => '15'],
    		['id' => '122', 'city' => 'Buenavista','department_id' => '23'],
    		['id' => '123', 'city' => 'Buenavista','department_id' => '63'],
    		['id' => '124', 'city' => 'Buenavista','department_id' => '70'],
    		['id' => '125', 'city' => 'Buenos Aires','department_id' => '19'],
    		['id' => '126', 'city' => 'Buesaco','department_id' => '52'],
    		['id' => '127', 'city' => 'Buga','department_id' => '76'],
    		['id' => '128', 'city' => 'Bugalagrande','department_id' => '76'],
    		['id' => '129', 'city' => 'Burítica','department_id' => '5'],
    		['id' => '130', 'city' => 'Busbanza','department_id' => '15'],
    		['id' => '131', 'city' => 'Cabrera','department_id' => '25'],
    		['id' => '132', 'city' => 'Cabrera','department_id' => '68'],
    		['id' => '133', 'city' => 'Cabuyaro','department_id' => '50'],
    		['id' => '134', 'city' => 'Cachipay','department_id' => '25'],
    		['id' => '135', 'city' => 'Caicedo','department_id' => '5'],
    		['id' => '136', 'city' => 'Caicedonia','department_id' => '76'],
    		['id' => '137', 'city' => 'Caimito','department_id' => '70'],
    		['id' => '138', 'city' => 'Cajamarca','department_id' => '73'],
    		['id' => '139', 'city' => 'Cajibío','department_id' => '19'],
    		['id' => '140', 'city' => 'Cajicá','department_id' => '25'],
    		['id' => '141', 'city' => 'Calamar','department_id' => '13'],
    		['id' => '142', 'city' => 'Calamar','department_id' => '95'],
    		['id' => '143', 'city' => 'Calarcá','department_id' => '63'],
    		['id' => '144', 'city' => 'Caldas','department_id' => '5'],
    		['id' => '145', 'city' => 'Caldas','department_id' => '15'],
    		['id' => '146', 'city' => 'Caldono','department_id' => '19'],
    		['id' => '147', 'city' => 'California','department_id' => '68'],
    		['id' => '148', 'city' => 'Calima (Darién)','department_id' => '76'],
    		['id' => '149', 'city' => 'Caloto','department_id' => '19'],
    		['id' => '150', 'city' => 'Calí','department_id' => '76'],
    		['id' => '151', 'city' => 'Campamento','department_id' => '5'],
    		['id' => '152', 'city' => 'Campo de la Cruz','department_id' => '8'],
    		['id' => '153', 'city' => 'Campoalegre','department_id' => '41'],
    		['id' => '154', 'city' => 'Campohermoso','department_id' => '15'],
    		['id' => '155', 'city' => 'Canalete','department_id' => '23'],
    		['id' => '156', 'city' => 'Candelaria','department_id' => '8'],
    		['id' => '157', 'city' => 'Candelaria','department_id' => '76'],
    		['id' => '158', 'city' => 'Cantagallo','department_id' => '13'],
    		['id' => '159', 'city' => 'Cantón de San Pablo','department_id' => '27'],
    		['id' => '160', 'city' => 'Caparrapí','department_id' => '25'],
    		['id' => '161', 'city' => 'Capitanejo','department_id' => '68'],
    		['id' => '162', 'city' => 'Caracolí','department_id' => '5'],
    		['id' => '163', 'city' => 'Caramanta','department_id' => '5'],
    		['id' => '164', 'city' => 'Carcasí','department_id' => '68'],
    		['id' => '165', 'city' => 'Carepa','department_id' => '5'],
    		['id' => '166', 'city' => 'Carmen de Apicalá','department_id' => '73'],
    		['id' => '167', 'city' => 'Carmen de Carupa','department_id' => '25'],
    		['id' => '168', 'city' => 'Carmen de Viboral','department_id' => '5'],
    		['id' => '169', 'city' => 'Carmen del Darién (CURBARADÓ)','department_id' => '27'],
    		['id' => '170', 'city' => 'Carolina','department_id' => '5'],
    		['id' => '171', 'city' => 'Cartagena','department_id' => '13'],
    		['id' => '172', 'city' => 'Cartagena del Chairá','department_id' => '18'],
    		['id' => '173', 'city' => 'Cartago','department_id' => '76'],
    		['id' => '174', 'city' => 'Carurú','department_id' => '97'],
    		['id' => '175', 'city' => 'Casabianca','department_id' => '73'],
    		['id' => '176', 'city' => 'Castilla la Nueva','department_id' => '50'],
    		['id' => '177', 'city' => 'Caucasia','department_id' => '5'],
    		['id' => '178', 'city' => 'Cañasgordas','department_id' => '5'],
    		['id' => '179', 'city' => 'Cepita','department_id' => '68'],
    		['id' => '180', 'city' => 'Cereté','department_id' => '23'],
    		['id' => '181', 'city' => 'Cerinza','department_id' => '15'],
    		['id' => '182', 'city' => 'Cerrito','department_id' => '68'],
    		['id' => '183', 'city' => 'Cerro San Antonio','department_id' => '47'],
    		['id' => '184', 'city' => 'Chachaguí','department_id' => '52'],
    		['id' => '185', 'city' => 'Chaguaní','department_id' => '25'],
    		['id' => '186', 'city' => 'Chalán','department_id' => '70'],
    		['id' => '187', 'city' => 'Chaparral','department_id' => '73'],
    		['id' => '188', 'city' => 'Charalá','department_id' => '68'],
    		['id' => '189', 'city' => 'Charta','department_id' => '68'],
    		['id' => '190', 'city' => 'Chigorodó','department_id' => '5'],
    		['id' => '191', 'city' => 'Chima','department_id' => '68'],
    		['id' => '192', 'city' => 'Chimichagua','department_id' => '20'],
    		['id' => '193', 'city' => 'Chimá','department_id' => '23'],
    		['id' => '194', 'city' => 'Chinavita','department_id' => '15'],
    		['id' => '195', 'city' => 'Chinchiná','department_id' => '17'],
    		['id' => '196', 'city' => 'Chinácota','department_id' => '54'],
    		['id' => '197', 'city' => 'Chinú','department_id' => '23'],
    		['id' => '198', 'city' => 'Chipaque','department_id' => '25'],
    		['id' => '199', 'city' => 'Chipatá','department_id' => '68'],
    		['id' => '200', 'city' => 'Chiquinquirá','department_id' => '15'],
    		['id' => '201', 'city' => 'Chiriguaná','department_id' => '20'],
    		['id' => '202', 'city' => 'Chiscas','department_id' => '15'],
    		['id' => '203', 'city' => 'Chita','department_id' => '15'],
    		['id' => '204', 'city' => 'Chitagá','department_id' => '54'],
    		['id' => '205', 'city' => 'Chitaraque','department_id' => '15'],
    		['id' => '206', 'city' => 'Chivatá','department_id' => '15'],
    		['id' => '207', 'city' => 'Chivolo','department_id' => '47'],
    		['id' => '208', 'city' => 'Choachí','department_id' => '25'],
    		['id' => '209', 'city' => 'Chocontá','department_id' => '25'],
    		['id' => '210', 'city' => 'Chámeza','department_id' => '85'],
    		['id' => '211', 'city' => 'Chía','department_id' => '25'],
    		['id' => '212', 'city' => 'Chíquiza','department_id' => '15'],
    		['id' => '213', 'city' => 'Chívor','department_id' => '15'],
    		['id' => '214', 'city' => 'Cicuco','department_id' => '13'],
    		['id' => '215', 'city' => 'Cimitarra','department_id' => '68'],
    		['id' => '216', 'city' => 'Circasia','department_id' => '63'],
    		['id' => '217', 'city' => 'Cisneros','department_id' => '5'],
    		['id' => '218', 'city' => 'Ciénaga','department_id' => '15'],
    		['id' => '219', 'city' => 'Ciénaga','department_id' => '47'],
    		['id' => '220', 'city' => 'Ciénaga de Oro','department_id' => '23'],
    		['id' => '221', 'city' => 'Clemencia','department_id' => '13'],
    		['id' => '222', 'city' => 'Cocorná','department_id' => '5'],
    		['id' => '223', 'city' => 'Coello','department_id' => '73'],
    		['id' => '224', 'city' => 'Cogua','department_id' => '25'],
    		['id' => '225', 'city' => 'Colombia','department_id' => '41'],
    		['id' => '226', 'city' => 'Colosó (Ricaurte)','department_id' => '70'],
    		['id' => '227', 'city' => 'Colón','department_id' => '86'],
    		['id' => '228', 'city' => 'Colón (Génova)','department_id' => '52'],
    		['id' => '229', 'city' => 'Concepción','department_id' => '5'],
    		['id' => '230', 'city' => 'Concepción','department_id' => '68'],
    		['id' => '231', 'city' => 'Concordia','department_id' => '5'],
    		['id' => '232', 'city' => 'Concordia','department_id' => '47'],
    		['id' => '233', 'city' => 'Condoto','department_id' => '27'],
    		['id' => '234', 'city' => 'Confines','department_id' => '68'],
    		['id' => '235', 'city' => 'Consaca','department_id' => '52'],
    		['id' => '236', 'city' => 'Contadero','department_id' => '52'],
    		['id' => '237', 'city' => 'Contratación','department_id' => '68'],
    		['id' => '238', 'city' => 'Convención','department_id' => '54'],
    		['id' => '239', 'city' => 'Copacabana','department_id' => '5'],
    		['id' => '240', 'city' => 'Coper','department_id' => '15'],
    		['id' => '241', 'city' => 'Cordobá','department_id' => '63'],
    		['id' => '242', 'city' => 'Corinto','department_id' => '19'],
    		['id' => '243', 'city' => 'Coromoro','department_id' => '68'],
    		['id' => '244', 'city' => 'Corozal','department_id' => '70'],
    		['id' => '245', 'city' => 'Corrales','department_id' => '15'],
    		['id' => '246', 'city' => 'Cota','department_id' => '25'],
    		['id' => '247', 'city' => 'Cotorra','department_id' => '23'],
    		['id' => '248', 'city' => 'Covarachía','department_id' => '15'],
    		['id' => '249', 'city' => 'Coveñas','department_id' => '70'],
    		['id' => '250', 'city' => 'Coyaima','department_id' => '73'],
    		['id' => '251', 'city' => 'Cravo Norte','department_id' => '81'],
    		['id' => '252', 'city' => 'Cuaspud (Carlosama)','department_id' => '52'],
    		['id' => '253', 'city' => 'Cubarral','department_id' => '50'],
    		['id' => '254', 'city' => 'Cubará','department_id' => '15'],
    		['id' => '255', 'city' => 'Cucaita','department_id' => '15'],
    		['id' => '256', 'city' => 'Cucunubá','department_id' => '25'],
    		['id' => '257', 'city' => 'Cucutilla','department_id' => '54'],
    		['id' => '258', 'city' => 'Cuitiva','department_id' => '15'],
    		['id' => '259', 'city' => 'Cumaral','department_id' => '50'],
    		['id' => '260', 'city' => 'Cumaribo','department_id' => '99'],
    		['id' => '261', 'city' => 'Cumbal','department_id' => '52'],
    		['id' => '262', 'city' => 'Cumbitara','department_id' => '52'],
    		['id' => '263', 'city' => 'Cunday','department_id' => '73'],
    		['id' => '264', 'city' => 'Curillo','department_id' => '18'],
    		['id' => '265', 'city' => 'Curití','department_id' => '68'],
    		['id' => '266', 'city' => 'Curumaní','department_id' => '20'],
    		['id' => '267', 'city' => 'Cáceres','department_id' => '5'],
    		['id' => '268', 'city' => 'Cáchira','department_id' => '54'],
    		['id' => '269', 'city' => 'Cácota','department_id' => '54'],
    		['id' => '270', 'city' => 'Cáqueza','department_id' => '25'],
    		['id' => '271', 'city' => 'Cértegui','department_id' => '27'],
    		['id' => '272', 'city' => 'Cómbita','department_id' => '15'],
    		['id' => '273', 'city' => 'Córdoba','department_id' => '13'],
    		['id' => '274', 'city' => 'Córdoba','department_id' => '52'],
    		['id' => '275', 'city' => 'Cúcuta','department_id' => '54'],
    		['id' => '276', 'city' => 'Dabeiba','department_id' => '5'],
    		['id' => '277', 'city' => 'Dagua','department_id' => '76'],
    		['id' => '278', 'city' => 'Dibulla','department_id' => '44'],
    		['id' => '279', 'city' => 'Distracción','department_id' => '44'],
    		['id' => '280', 'city' => 'Dolores','department_id' => '73'],
    		['id' => '281', 'city' => 'Don Matías','department_id' => '5'],
    		['id' => '282', 'city' => 'Dos Quebradas','department_id' => '66'],
    		['id' => '283', 'city' => 'Duitama','department_id' => '15'],
    		['id' => '284', 'city' => 'Durania','department_id' => '54'],
    		['id' => '285', 'city' => 'Ebéjico','department_id' => '5'],
    		['id' => '286', 'city' => 'El Bagre','department_id' => '5'],
    		['id' => '287', 'city' => 'El Banco','department_id' => '47'],
    		['id' => '288', 'city' => 'El Cairo','department_id' => '76'],
    		['id' => '289', 'city' => 'El Calvario','department_id' => '50'],
    		['id' => '290', 'city' => 'El Carmen','department_id' => '54'],
    		['id' => '291', 'city' => 'El Carmen','department_id' => '68'],
    		['id' => '292', 'city' => 'El Carmen de Atrato','department_id' => '27'],
    		['id' => '293', 'city' => 'El Carmen de Bolívar','department_id' => '13'],
    		['id' => '294', 'city' => 'El Castillo','department_id' => '50'],
    		['id' => '295', 'city' => 'El Cerrito','department_id' => '76'],
    		['id' => '296', 'city' => 'El Charco','department_id' => '52'],
    		['id' => '297', 'city' => 'El Cocuy','department_id' => '15'],
    		['id' => '298', 'city' => 'El Colegio','department_id' => '25'],
    		['id' => '299', 'city' => 'El Copey','department_id' => '20'],
    		['id' => '300', 'city' => 'El Doncello','department_id' => '18'],
    		['id' => '301', 'city' => 'El Dorado','department_id' => '50'],
    		['id' => '302', 'city' => 'El Dovio','department_id' => '76'],
    		['id' => '303', 'city' => 'El Espino','department_id' => '15'],
    		['id' => '304', 'city' => 'El Guacamayo','department_id' => '68'],
    		['id' => '305', 'city' => 'El Guamo','department_id' => '13'],
    		['id' => '306', 'city' => 'El Molino','department_id' => '44'],
    		['id' => '307', 'city' => 'El Paso','department_id' => '20'],
    		['id' => '308', 'city' => 'El Paujil','department_id' => '18'],
    		['id' => '309', 'city' => 'El Peñol','department_id' => '52'],
    		['id' => '310', 'city' => 'El Peñon','department_id' => '13'],
    		['id' => '311', 'city' => 'El Peñon','department_id' => '68'],
    		['id' => '312', 'city' => 'El Peñón','department_id' => '25'],
    		['id' => '313', 'city' => 'El Piñon','department_id' => '47'],
    		['id' => '314', 'city' => 'El Playón','department_id' => '68'],
    		['id' => '315', 'city' => 'El Retorno','department_id' => '95'],
    		['id' => '316', 'city' => 'El Retén','department_id' => '47'],
    		['id' => '317', 'city' => 'El Roble','department_id' => '70'],
    		['id' => '318', 'city' => 'El Rosal','department_id' => '25'],
    		['id' => '319', 'city' => 'El Rosario','department_id' => '52'],
    		['id' => '320', 'city' => 'El Tablón de Gómez','department_id' => '52'],
    		['id' => '321', 'city' => 'El Tambo','department_id' => '19'],
    		['id' => '322', 'city' => 'El Tambo','department_id' => '52'],
    		['id' => '323', 'city' => 'El Tarra','department_id' => '54'],
    		['id' => '324', 'city' => 'El Zulia','department_id' => '54'],
    		['id' => '325', 'city' => 'El Águila','department_id' => '76'],
    		['id' => '326', 'city' => 'Elías','department_id' => '41'],
    		['id' => '327', 'city' => 'Encino','department_id' => '68'],
    		['id' => '328', 'city' => 'Enciso','department_id' => '68'],
    		['id' => '329', 'city' => 'Entrerríos','department_id' => '5'],
    		['id' => '330', 'city' => 'Envigado','department_id' => '5'],
    		['id' => '331', 'city' => 'Espinal','department_id' => '73'],
    		['id' => '332', 'city' => 'Facatativá','department_id' => '25'],
    		['id' => '333', 'city' => 'Falan','department_id' => '73'],
    		['id' => '334', 'city' => 'Filadelfia','department_id' => '17'],
    		['id' => '335', 'city' => 'Filandia','department_id' => '63'],
    		['id' => '336', 'city' => 'Firavitoba','department_id' => '15'],
    		['id' => '337', 'city' => 'Flandes','department_id' => '73'],
    		['id' => '338', 'city' => 'Florencia','department_id' => '18'],
    		['id' => '339', 'city' => 'Florencia','department_id' => '19'],
    		['id' => '340', 'city' => 'Floresta','department_id' => '15'],
    		['id' => '341', 'city' => 'Florida','department_id' => '76'],
    		['id' => '342', 'city' => 'Floridablanca','department_id' => '68'],
    		['id' => '343', 'city' => 'Florián','department_id' => '68'],
    		['id' => '344', 'city' => 'Fonseca','department_id' => '44'],
    		['id' => '345', 'city' => 'Fortúl','department_id' => '81'],
    		['id' => '346', 'city' => 'Fosca','department_id' => '25'],
    		['id' => '347', 'city' => 'Francisco Pizarro','department_id' => '52'],
    		['id' => '348', 'city' => 'Fredonia','department_id' => '5'],
    		['id' => '349', 'city' => 'Fresno','department_id' => '73'],
    		['id' => '350', 'city' => 'Frontino','department_id' => '5'],
    		['id' => '351', 'city' => 'Fuente de Oro','department_id' => '50'],
    		['id' => '352', 'city' => 'Fundación','department_id' => '47'],
    		['id' => '353', 'city' => 'Funes','department_id' => '52'],
    		['id' => '354', 'city' => 'Funza','department_id' => '25'],
    		['id' => '355', 'city' => 'Fusagasugá','department_id' => '25'],
    		['id' => '356', 'city' => 'Fómeque','department_id' => '25'],
    		['id' => '357', 'city' => 'Fúquene','department_id' => '25'],
    		['id' => '358', 'city' => 'Gachalá','department_id' => '25'],
    		['id' => '359', 'city' => 'Gachancipá','department_id' => '25'],
    		['id' => '360', 'city' => 'Gachantivá','department_id' => '15'],
    		['id' => '361', 'city' => 'Gachetá','department_id' => '25'],
    		['id' => '362', 'city' => 'Galapa','department_id' => '8'],
    		['id' => '363', 'city' => 'Galeras (Nueva Granada)','department_id' => '70'],
    		['id' => '364', 'city' => 'Galán','department_id' => '68'],
    		['id' => '365', 'city' => 'Gama','department_id' => '25'],
    		['id' => '366', 'city' => 'Gamarra','department_id' => '20'],
    		['id' => '367', 'city' => 'Garagoa','department_id' => '15'],
    		['id' => '368', 'city' => 'Garzón','department_id' => '41'],
    		['id' => '369', 'city' => 'Gigante','department_id' => '41'],
    		['id' => '370', 'city' => 'Ginebra','department_id' => '76'],
    		['id' => '371', 'city' => 'Giraldo','department_id' => '5'],
    		['id' => '372', 'city' => 'Girardot','department_id' => '25'],
    		['id' => '373', 'city' => 'Girardota','department_id' => '5'],
    		['id' => '374', 'city' => 'Girón','department_id' => '68'],
    		['id' => '375', 'city' => 'Gonzalez','department_id' => '20'],
    		['id' => '376', 'city' => 'Gramalote','department_id' => '54'],
    		['id' => '377', 'city' => 'Granada','department_id' => '5'],
    		['id' => '378', 'city' => 'Granada','department_id' => '25'],
    		['id' => '379', 'city' => 'Granada','department_id' => '50'],
    		['id' => '380', 'city' => 'Guaca','department_id' => '68'],
    		['id' => '381', 'city' => 'Guacamayas','department_id' => '15'],
    		['id' => '382', 'city' => 'Guacarí','department_id' => '76'],
    		['id' => '383', 'city' => 'Guachavés','department_id' => '52'],
    		['id' => '384', 'city' => 'Guachené','department_id' => '19'],
    		['id' => '385', 'city' => 'Guachetá','department_id' => '25'],
    		['id' => '386', 'city' => 'Guachucal','department_id' => '52'],
    		['id' => '387', 'city' => 'Guadalupe','department_id' => '5'],
    		['id' => '388', 'city' => 'Guadalupe','department_id' => '41'],
    		['id' => '389', 'city' => 'Guadalupe','department_id' => '68'],
    		['id' => '390', 'city' => 'Guaduas','department_id' => '25'],
    		['id' => '391', 'city' => 'Guaitarilla','department_id' => '52'],
    		['id' => '392', 'city' => 'Gualmatán','department_id' => '52'],
    		['id' => '393', 'city' => 'Guamal','department_id' => '47'],
    		['id' => '394', 'city' => 'Guamal','department_id' => '50'],
    		['id' => '395', 'city' => 'Guamo','department_id' => '73'],
    		['id' => '396', 'city' => 'Guapota','department_id' => '68'],
    		['id' => '397', 'city' => 'Guapí','department_id' => '19'],
    		['id' => '398', 'city' => 'Guaranda','department_id' => '70'],
    		['id' => '399', 'city' => 'Guarne','department_id' => '5'],
    		['id' => '400', 'city' => 'Guasca','department_id' => '25'],
    		['id' => '401', 'city' => 'Guatapé','department_id' => '5'],
    		['id' => '402', 'city' => 'Guataquí','department_id' => '25'],
    		['id' => '403', 'city' => 'Guatavita','department_id' => '25'],
    		['id' => '404', 'city' => 'Guateque','department_id' => '15'],
    		['id' => '405', 'city' => 'Guavatá','department_id' => '68'],
    		['id' => '406', 'city' => 'Guayabal de Siquima','department_id' => '25'],
    		['id' => '407', 'city' => 'Guayabetal','department_id' => '25'],
    		['id' => '408', 'city' => 'Guayatá','department_id' => '15'],
    		['id' => '409', 'city' => 'Guepsa','department_id' => '68'],
    		['id' => '410', 'city' => 'Guicán','department_id' => '15'],
    		['id' => '411', 'city' => 'Gutiérrez','department_id' => '25'],
    		['id' => '412', 'city' => 'Guática','department_id' => '66'],
    		['id' => '413', 'city' => 'Gámbita','department_id' => '68'],
    		['id' => '414', 'city' => 'Gámeza','department_id' => '15'],
    		['id' => '415', 'city' => 'Génova','department_id' => '63'],
    		['id' => '416', 'city' => 'Gómez Plata','department_id' => '5'],
    		['id' => '417', 'city' => 'Hacarí','department_id' => '54'],
    		['id' => '418', 'city' => 'Hatillo de Loba','department_id' => '13'],
    		['id' => '419', 'city' => 'Hato','department_id' => '68'],
    		['id' => '420', 'city' => 'Hato Corozal','department_id' => '85'],
    		['id' => '421', 'city' => 'Hatonuevo','department_id' => '44'],
    		['id' => '422', 'city' => 'Heliconia','department_id' => '5'],
    		['id' => '423', 'city' => 'Herrán','department_id' => '54'],
    		['id' => '424', 'city' => 'Herveo','department_id' => '73'],
    		['id' => '425', 'city' => 'Hispania','department_id' => '5'],
    		['id' => '426', 'city' => 'Hobo','department_id' => '41'],
    		['id' => '427', 'city' => 'Honda','department_id' => '73'],
    		['id' => '428', 'city' => 'Ibagué','department_id' => '73'],
    		['id' => '429', 'city' => 'Icononzo','department_id' => '73'],
    		['id' => '430', 'city' => 'Iles','department_id' => '52'],
    		['id' => '431', 'city' => 'Imúes','department_id' => '52'],
    		['id' => '432', 'city' => 'Inzá','department_id' => '19'],
    		['id' => '433', 'city' => 'Inírida','department_id' => '94'],
    		['id' => '434', 'city' => 'Ipiales','department_id' => '52'],
    		['id' => '435', 'city' => 'Isnos','department_id' => '41'],
    		['id' => '436', 'city' => 'Istmina','department_id' => '27'],
    		['id' => '437', 'city' => 'Itagüí','department_id' => '5'],
    		['id' => '438', 'city' => 'Ituango','department_id' => '5'],
    		['id' => '439', 'city' => 'Izá','department_id' => '15'],
    		['id' => '440', 'city' => 'Jambaló','department_id' => '19'],
    		['id' => '441', 'city' => 'Jamundí','department_id' => '76'],
    		['id' => '442', 'city' => 'Jardín','department_id' => '5'],
    		['id' => '443', 'city' => 'Jenesano','department_id' => '15'],
    		['id' => '444', 'city' => 'Jericó','department_id' => '5'],
    		['id' => '445', 'city' => 'Jericó','department_id' => '15'],
    		['id' => '446', 'city' => 'Jerusalén','department_id' => '25'],
    		['id' => '447', 'city' => 'Jesús María','department_id' => '68'],
    		['id' => '448', 'city' => 'Jordán','department_id' => '68'],
    		['id' => '449', 'city' => 'Juan de Acosta','department_id' => '8'],
    		['id' => '450', 'city' => 'Junín','department_id' => '25'],
    		['id' => '451', 'city' => 'Juradó','department_id' => '27'],
    		['id' => '452', 'city' => 'La Apartada y La Frontera','department_id' => '23'],
    		['id' => '453', 'city' => 'La Argentina','department_id' => '41'],
    		['id' => '454', 'city' => 'La Belleza','department_id' => '68'],
    		['id' => '455', 'city' => 'La Calera','department_id' => '25'],
    		['id' => '456', 'city' => 'La Capilla','department_id' => '15'],
    		['id' => '457', 'city' => 'La Ceja','department_id' => '5'],
    		['id' => '458', 'city' => 'La Celia','department_id' => '66'],
    		['id' => '459', 'city' => 'La Cruz','department_id' => '52'],
    		['id' => '460', 'city' => 'La Cumbre','department_id' => '76'],
    		['id' => '461', 'city' => 'La Dorada','department_id' => '17'],
    		['id' => '462', 'city' => 'La Esperanza','department_id' => '54'],
    		['id' => '463', 'city' => 'La Estrella','department_id' => '5'],
    		['id' => '464', 'city' => 'La Florida','department_id' => '52'],
    		['id' => '465', 'city' => 'La Gloria','department_id' => '20'],
    		['id' => '466', 'city' => 'La Jagua de Ibirico','department_id' => '20'],
    		['id' => '467', 'city' => 'La Jagua del Pilar','department_id' => '44'],
    		['id' => '468', 'city' => 'La Llanada','department_id' => '52'],
    		['id' => '469', 'city' => 'La Macarena','department_id' => '50'],
    		['id' => '470', 'city' => 'La Merced','department_id' => '17'],
    		['id' => '471', 'city' => 'La Mesa','department_id' => '25'],
    		['id' => '472', 'city' => 'La Montañita','department_id' => '18'],
    		['id' => '473', 'city' => 'La Palma','department_id' => '25'],
    		['id' => '474', 'city' => 'La Paz','department_id' => '68'],
    		['id' => '475', 'city' => 'La Paz (Robles)','department_id' => '20'],
    		['id' => '476', 'city' => 'La Peña','department_id' => '25'],
    		['id' => '477', 'city' => 'La Pintada','department_id' => '5'],
    		['id' => '478', 'city' => 'La Plata','department_id' => '41'],
    		['id' => '479', 'city' => 'La Playa','department_id' => '54'],
    		['id' => '480', 'city' => 'La Primavera','department_id' => '99'],
    		['id' => '481', 'city' => 'La Salina','department_id' => '85'],
    		['id' => '482', 'city' => 'La Sierra','department_id' => '19'],
    		['id' => '483', 'city' => 'La Tebaida','department_id' => '63'],
    		['id' => '484', 'city' => 'La Tola','department_id' => '52'],
    		['id' => '485', 'city' => 'La Unión','department_id' => '5'],
    		['id' => '486', 'city' => 'La Unión','department_id' => '52'],
    		['id' => '487', 'city' => 'La Unión','department_id' => '70'],
    		['id' => '488', 'city' => 'La Unión','department_id' => '76'],
    		['id' => '489', 'city' => 'La Uvita','department_id' => '15'],
    		['id' => '490', 'city' => 'La Vega','department_id' => '19'],
    		['id' => '491', 'city' => 'La Vega','department_id' => '25'],
    		['id' => '492', 'city' => 'La Victoria','department_id' => '15'],
    		['id' => '493', 'city' => 'La Victoria','department_id' => '17'],
    		['id' => '494', 'city' => 'La Victoria','department_id' => '76'],
    		['id' => '495', 'city' => 'La Virginia','department_id' => '66'],
    		['id' => '496', 'city' => 'Labateca','department_id' => '54'],
    		['id' => '497', 'city' => 'Labranzagrande','department_id' => '15'],
    		['id' => '498', 'city' => 'Landázuri','department_id' => '68'],
    		['id' => '499', 'city' => 'Lebrija','department_id' => '68'],
    		['id' => '500', 'city' => 'Leiva','department_id' => '52'],
    		['id' => '501', 'city' => 'Lejanías','department_id' => '50'],
    		['id' => '502', 'city' => 'Lenguazaque','department_id' => '25'],
    		['id' => '503', 'city' => 'Leticia','department_id' => '91'],
    		['id' => '504', 'city' => 'Liborina','department_id' => '5'],
    		['id' => '505', 'city' => 'Linares','department_id' => '52'],
    		['id' => '506', 'city' => 'Lloró','department_id' => '27'],
    		['id' => '507', 'city' => 'Lorica','department_id' => '23'],
    		['id' => '508', 'city' => 'Los Córdobas','department_id' => '23'],
    		['id' => '509', 'city' => 'Los Palmitos','department_id' => '70'],
    		['id' => '510', 'city' => 'Los Patios','department_id' => '54'],
    		['id' => '511', 'city' => 'Los Santos','department_id' => '68'],
    		['id' => '512', 'city' => 'Lourdes','department_id' => '54'],
    		['id' => '513', 'city' => 'Luruaco','department_id' => '8'],
    		['id' => '514', 'city' => 'Lérida','department_id' => '73'],
    		['id' => '515', 'city' => 'Líbano','department_id' => '73'],
    		['id' => '516', 'city' => 'López (Micay)','department_id' => '19'],
    		['id' => '517', 'city' => 'Macanal','department_id' => '15'],
    		['id' => '518', 'city' => 'Macaravita','department_id' => '68'],
    		['id' => '519', 'city' => 'Maceo','department_id' => '5'],
    		['id' => '520', 'city' => 'Machetá','department_id' => '25'],
    		['id' => '521', 'city' => 'Madrid','department_id' => '25'],
    		['id' => '522', 'city' => 'Magangué','department_id' => '13'],
    		['id' => '523', 'city' => 'Magüi (Payán)','department_id' => '52'],
    		['id' => '524', 'city' => 'Mahates','department_id' => '13'],
    		['id' => '525', 'city' => 'Maicao','department_id' => '44'],
    		['id' => '526', 'city' => 'Majagual','department_id' => '70'],
    		['id' => '527', 'city' => 'Malambo','department_id' => '8'],
    		['id' => '528', 'city' => 'Mallama (Piedrancha)','department_id' => '52'],
    		['id' => '529', 'city' => 'Manatí','department_id' => '8'],
    		['id' => '530', 'city' => 'Manaure','department_id' => '44'],
    		['id' => '531', 'city' => 'Manaure Balcón del Cesar','department_id' => '20'],
    		['id' => '532', 'city' => 'Manizales','department_id' => '17'],
    		['id' => '533', 'city' => 'Manta','department_id' => '25'],
    		['id' => '534', 'city' => 'Manzanares','department_id' => '17'],
    		['id' => '535', 'city' => 'Maní','department_id' => '85'],
    		['id' => '536', 'city' => 'Mapiripan','department_id' => '50'],
    		['id' => '537', 'city' => 'Margarita','department_id' => '13'],
    		['id' => '538', 'city' => 'Marinilla','department_id' => '5'],
    		['id' => '539', 'city' => 'Maripí','department_id' => '15'],
    		['id' => '540', 'city' => 'Mariquita','department_id' => '73'],
    		['id' => '541', 'city' => 'Marmato','department_id' => '17'],
    		['id' => '542', 'city' => 'Marquetalia','department_id' => '17'],
    		['id' => '543', 'city' => 'Marsella','department_id' => '66'],
    		['id' => '544', 'city' => 'Marulanda','department_id' => '17'],
    		['id' => '545', 'city' => 'María la Baja','department_id' => '13'],
    		['id' => '546', 'city' => 'Matanza','department_id' => '68'],
    		['id' => '547', 'city' => 'Medellín','department_id' => '5'],
    		['id' => '548', 'city' => 'Medina','department_id' => '25'],
    		['id' => '549', 'city' => 'Medio Atrato','department_id' => '27'],
    		['id' => '550', 'city' => 'Medio Baudó','department_id' => '27'],
    		['id' => '551', 'city' => 'Medio San Juan (ANDAGOYA)','department_id' => '27'],
    		['id' => '552', 'city' => 'Melgar','department_id' => '73'],
    		['id' => '553', 'city' => 'Mercaderes','department_id' => '19'],
    		['id' => '554', 'city' => 'Mesetas','department_id' => '50'],
    		['id' => '555', 'city' => 'Milán','department_id' => '18'],
    		['id' => '556', 'city' => 'Miraflores','department_id' => '15'],
    		['id' => '557', 'city' => 'Miraflores','department_id' => '95'],
    		['id' => '558', 'city' => 'Miranda','department_id' => '19'],
    		['id' => '559', 'city' => 'Mistrató','department_id' => '66'],
    		['id' => '560', 'city' => 'Mitú','department_id' => '97'],
    		['id' => '561', 'city' => 'Mocoa','department_id' => '86'],
    		['id' => '562', 'city' => 'Mogotes','department_id' => '68'],
    		['id' => '563', 'city' => 'Molagavita','department_id' => '68'],
    		['id' => '564', 'city' => 'Momil','department_id' => '23'],
    		['id' => '565', 'city' => 'Mompós','department_id' => '13'],
    		['id' => '566', 'city' => 'Mongua','department_id' => '15'],
    		['id' => '567', 'city' => 'Monguí','department_id' => '15'],
    		['id' => '568', 'city' => 'Moniquirá','department_id' => '15'],
    		['id' => '569', 'city' => 'Montebello','department_id' => '5'],
    		['id' => '570', 'city' => 'Montecristo','department_id' => '13'],
    		['id' => '571', 'city' => 'Montelíbano','department_id' => '23'],
    		['id' => '572', 'city' => 'Montenegro','department_id' => '63'],
    		['id' => '573', 'city' => 'Monteria','department_id' => '23'],
    		['id' => '574', 'city' => 'Monterrey','department_id' => '85'],
    		['id' => '575', 'city' => 'Morales','department_id' => '13'],
    		['id' => '576', 'city' => 'Morales','department_id' => '19'],
    		['id' => '577', 'city' => 'Morelia','department_id' => '18'],
    		['id' => '578', 'city' => 'Morroa','department_id' => '70'],
    		['id' => '579', 'city' => 'Mosquera','department_id' => '25'],
    		['id' => '580', 'city' => 'Mosquera','department_id' => '52'],
    		['id' => '581', 'city' => 'Motavita','department_id' => '15'],
    		['id' => '582', 'city' => 'Moñitos','department_id' => '23'],
    		['id' => '583', 'city' => 'Murillo','department_id' => '73'],
    		['id' => '584', 'city' => 'Murindó','department_id' => '5'],
    		['id' => '585', 'city' => 'Mutatá','department_id' => '5'],
    		['id' => '586', 'city' => 'Mutiscua','department_id' => '54'],
    		['id' => '587', 'city' => 'Muzo','department_id' => '15'],
    		['id' => '588', 'city' => 'Málaga','department_id' => '68'],
    		['id' => '589', 'city' => 'Nariño','department_id' => '5'],
    		['id' => '590', 'city' => 'Nariño','department_id' => '25'],
    		['id' => '591', 'city' => 'Nariño','department_id' => '52'],
    		['id' => '592', 'city' => 'Natagaima','department_id' => '73'],
    		['id' => '593', 'city' => 'Nechí','department_id' => '5'],
    		['id' => '594', 'city' => 'Necoclí','department_id' => '5'],
    		['id' => '595', 'city' => 'Neira','department_id' => '17'],
    		['id' => '596', 'city' => 'Neiva','department_id' => '41'],
    		['id' => '597', 'city' => 'Nemocón','department_id' => '25'],
    		['id' => '598', 'city' => 'Nilo','department_id' => '25'],
    		['id' => '599', 'city' => 'Nimaima','department_id' => '25'],
    		['id' => '600', 'city' => 'Nobsa','department_id' => '15'],
    		['id' => '601', 'city' => 'Nocaima','department_id' => '25'],
    		['id' => '602', 'city' => 'Norcasia','department_id' => '17'],
    		['id' => '603', 'city' => 'Norosí','department_id' => '13'],
    		['id' => '604', 'city' => 'Novita','department_id' => '27'],
    		['id' => '605', 'city' => 'Nueva Granada','department_id' => '47'],
    		['id' => '606', 'city' => 'Nuevo Colón','department_id' => '15'],
    		['id' => '607', 'city' => 'Nunchía','department_id' => '85'],
    		['id' => '608', 'city' => 'Nuquí','department_id' => '27'],
    		['id' => '609', 'city' => 'Nátaga','department_id' => '41'],
    		['id' => '610', 'city' => 'Obando','department_id' => '76'],
    		['id' => '611', 'city' => 'Ocamonte','department_id' => '68'],
    		['id' => '612', 'city' => 'Ocaña','department_id' => '54'],
    		['id' => '613', 'city' => 'Oiba','department_id' => '68'],
    		['id' => '614', 'city' => 'Oicatá','department_id' => '15'],
    		['id' => '615', 'city' => 'Olaya','department_id' => '5'],
    		['id' => '616', 'city' => 'Olaya Herrera','department_id' => '52'],
    		['id' => '617', 'city' => 'Onzaga','department_id' => '68'],
    		['id' => '618', 'city' => 'Oporapa','department_id' => '41'],
    		['id' => '619', 'city' => 'Orito','department_id' => '86'],
    		['id' => '620', 'city' => 'Orocué','department_id' => '85'],
    		['id' => '621', 'city' => 'Ortega','department_id' => '73'],
    		['id' => '622', 'city' => 'Ospina','department_id' => '52'],
    		['id' => '623', 'city' => 'Otanche','department_id' => '15'],
    		['id' => '624', 'city' => 'Ovejas','department_id' => '70'],
    		['id' => '625', 'city' => 'Pachavita','department_id' => '15'],
    		['id' => '626', 'city' => 'Pacho','department_id' => '25'],
    		['id' => '627', 'city' => 'Padilla','department_id' => '19'],
    		['id' => '628', 'city' => 'Paicol','department_id' => '41'],
    		['id' => '629', 'city' => 'Pailitas','department_id' => '20'],
    		['id' => '630', 'city' => 'Paime','department_id' => '25'],
    		['id' => '631', 'city' => 'Paipa','department_id' => '15'],
    		['id' => '632', 'city' => 'Pajarito','department_id' => '15'],
    		['id' => '633', 'city' => 'Palermo','department_id' => '41'],
    		['id' => '634', 'city' => 'Palestina','department_id' => '17'],
    		['id' => '635', 'city' => 'Palestina','department_id' => '41'],
    		['id' => '636', 'city' => 'Palmar','department_id' => '68'],
    		['id' => '637', 'city' => 'Palmar de Varela','department_id' => '8'],
    		['id' => '638', 'city' => 'Palmas del Socorro','department_id' => '68'],
    		['id' => '639', 'city' => 'Palmira','department_id' => '76'],
    		['id' => '640', 'city' => 'Palmito','department_id' => '70'],
    		['id' => '641', 'city' => 'Palocabildo','department_id' => '73'],
    		['id' => '642', 'city' => 'Pamplona','department_id' => '54'],
    		['id' => '643', 'city' => 'Pamplonita','department_id' => '54'],
    		['id' => '644', 'city' => 'Pandi','department_id' => '25'],
    		['id' => '645', 'city' => 'Panqueba','department_id' => '15'],
    		['id' => '646', 'city' => 'Paratebueno','department_id' => '25'],
    		['id' => '647', 'city' => 'Pasca','department_id' => '25'],
    		['id' => '648', 'city' => 'Patía (El Bordo)','department_id' => '19'],
    		['id' => '649', 'city' => 'Pauna','department_id' => '15'],
    		['id' => '650', 'city' => 'Paya','department_id' => '15'],
    		['id' => '651', 'city' => 'Paz de Ariporo','department_id' => '85'],
    		['id' => '652', 'city' => 'Paz de Río','department_id' => '15'],
    		['id' => '653', 'city' => 'Pedraza','department_id' => '47'],
    		['id' => '654', 'city' => 'Pelaya','department_id' => '20'],
    		['id' => '655', 'city' => 'Pensilvania','department_id' => '17'],
    		['id' => '656', 'city' => 'Peque','department_id' => '5'],
    		['id' => '657', 'city' => 'Pereira','department_id' => '66'],
    		['id' => '658', 'city' => 'Pesca','department_id' => '15'],
    		['id' => '659', 'city' => 'Peñol','department_id' => '5'],
    		['id' => '660', 'city' => 'Piamonte','department_id' => '19'],
    		['id' => '661', 'city' => 'Pie de Cuesta','department_id' => '68'],
    		['id' => '662', 'city' => 'Piedras','department_id' => '73'],
    		['id' => '663', 'city' => 'Piendamó','department_id' => '19'],
    		['id' => '664', 'city' => 'Pijao','department_id' => '63'],
    		['id' => '665', 'city' => 'Pijiño','department_id' => '47'],
    		['id' => '666', 'city' => 'Pinchote','department_id' => '68'],
    		['id' => '667', 'city' => 'Pinillos','department_id' => '13'],
    		['id' => '668', 'city' => 'Piojo','department_id' => '8'],
    		['id' => '669', 'city' => 'Pisva','department_id' => '15'],
    		['id' => '670', 'city' => 'Pital','department_id' => '41'],
    		['id' => '671', 'city' => 'Pitalito','department_id' => '41'],
    		['id' => '672', 'city' => 'Pivijay','department_id' => '47'],
    		['id' => '673', 'city' => 'Planadas','department_id' => '73'],
    		['id' => '674', 'city' => 'Planeta Rica','department_id' => '23'],
    		['id' => '675', 'city' => 'Plato','department_id' => '47'],
    		['id' => '676', 'city' => 'Policarpa','department_id' => '52'],
    		['id' => '677', 'city' => 'Polonuevo','department_id' => '8'],
    		['id' => '678', 'city' => 'Ponedera','department_id' => '8'],
    		['id' => '679', 'city' => 'Popayán','department_id' => '19'],
    		['id' => '680', 'city' => 'Pore','department_id' => '85'],
    		['id' => '681', 'city' => 'Potosí','department_id' => '52'],
    		['id' => '682', 'city' => 'Pradera','department_id' => '76'],
    		['id' => '683', 'city' => 'Prado','department_id' => '73'],
    		['id' => '684', 'city' => 'Providencia','department_id' => '52'],
    		['id' => '685', 'city' => 'Providencia','department_id' => '88'],
    		['id' => '686', 'city' => 'Pueblo Bello','department_id' => '20'],
    		['id' => '687', 'city' => 'Pueblo Nuevo','department_id' => '23'],
    		['id' => '688', 'city' => 'Pueblo Rico','department_id' => '66'],
    		['id' => '689', 'city' => 'Pueblorrico','department_id' => '5'],
    		['id' => '690', 'city' => 'Puebloviejo','department_id' => '47'],
    		['id' => '691', 'city' => 'Puente Nacional','department_id' => '68'],
    		['id' => '692', 'city' => 'Puerres','department_id' => '52'],
    		['id' => '693', 'city' => 'Puerto Asís','department_id' => '86'],
    		['id' => '694', 'city' => 'Puerto Berrío','department_id' => '5'],
    		['id' => '695', 'city' => 'Puerto Boyacá','department_id' => '15'],
    		['id' => '696', 'city' => 'Puerto Caicedo','department_id' => '86'],
    		['id' => '697', 'city' => 'Puerto Carreño','department_id' => '99'],
    		['id' => '698', 'city' => 'Puerto Colombia','department_id' => '8'],
    		['id' => '699', 'city' => 'Puerto Concordia','department_id' => '50'],
    		['id' => '700', 'city' => 'Puerto Escondido','department_id' => '23'],
    		['id' => '701', 'city' => 'Puerto Gaitán','department_id' => '50'],
    		['id' => '702', 'city' => 'Puerto Guzmán','department_id' => '86'],
    		['id' => '703', 'city' => 'Puerto Leguízamo','department_id' => '86'],
    		['id' => '704', 'city' => 'Puerto Libertador','department_id' => '23'],
    		['id' => '705', 'city' => 'Puerto Lleras','department_id' => '50'],
    		['id' => '706', 'city' => 'Puerto López','department_id' => '50'],
    		['id' => '707', 'city' => 'Puerto Nare','department_id' => '5'],
    		['id' => '708', 'city' => 'Puerto Nariño','department_id' => '91'],
    		['id' => '709', 'city' => 'Puerto Parra','department_id' => '68'],
    		['id' => '710', 'city' => 'Puerto Rico','department_id' => '18'],
    		['id' => '711', 'city' => 'Puerto Rico','department_id' => '50'],
    		['id' => '712', 'city' => 'Puerto Rondón','department_id' => '81'],
    		['id' => '713', 'city' => 'Puerto Salgar','department_id' => '25'],
    		['id' => '714', 'city' => 'Puerto Santander','department_id' => '54'],
    		['id' => '715', 'city' => 'Puerto Tejada','department_id' => '19'],
    		['id' => '716', 'city' => 'Puerto Triunfo','department_id' => '5'],
    		['id' => '717', 'city' => 'Puerto Wilches','department_id' => '68'],
    		['id' => '718', 'city' => 'Pulí','department_id' => '25'],
    		['id' => '719', 'city' => 'Pupiales','department_id' => '52'],
    		['id' => '720', 'city' => 'Puracé (Coconuco)','department_id' => '19'],
    		['id' => '721', 'city' => 'Purificación','department_id' => '73'],
    		['id' => '722', 'city' => 'Purísima','department_id' => '23'],
    		['id' => '723', 'city' => 'Pácora','department_id' => '17'],
    		['id' => '724', 'city' => 'Páez','department_id' => '15'],
    		['id' => '725', 'city' => 'Páez (Belalcazar)','department_id' => '19'],
    		['id' => '726', 'city' => 'Páramo','department_id' => '68'],
    		['id' => '727', 'city' => 'Quebradanegra','department_id' => '25'],
    		['id' => '728', 'city' => 'Quetame','department_id' => '25'],
    		['id' => '729', 'city' => 'Quibdó','department_id' => '27'],
    		['id' => '730', 'city' => 'Quimbaya','department_id' => '63'],
    		['id' => '731', 'city' => 'Quinchía','department_id' => '66'],
    		['id' => '732', 'city' => 'Quipama','department_id' => '15'],
    		['id' => '733', 'city' => 'Quipile','department_id' => '25'],
    		['id' => '734', 'city' => 'Ragonvalia','department_id' => '54'],
    		['id' => '735', 'city' => 'Ramiriquí','department_id' => '15'],
    		['id' => '736', 'city' => 'Recetor','department_id' => '85'],
    		['id' => '737', 'city' => 'Regidor','department_id' => '13'],
    		['id' => '738', 'city' => 'Remedios','department_id' => '5'],
    		['id' => '739', 'city' => 'Remolino','department_id' => '47'],
    		['id' => '740', 'city' => 'Repelón','department_id' => '8'],
    		['id' => '741', 'city' => 'Restrepo','department_id' => '50'],
    		['id' => '742', 'city' => 'Restrepo','department_id' => '76'],
    		['id' => '743', 'city' => 'Retiro','department_id' => '5'],
    		['id' => '744', 'city' => 'Ricaurte','department_id' => '25'],
    		['id' => '745', 'city' => 'Ricaurte','department_id' => '52'],
    		['id' => '746', 'city' => 'Rio Negro','department_id' => '68'],
    		['id' => '747', 'city' => 'Rioblanco','department_id' => '73'],
    		['id' => '748', 'city' => 'Riofrío','department_id' => '76'],
    		['id' => '749', 'city' => 'Riohacha','department_id' => '44'],
    		['id' => '750', 'city' => 'Risaralda','department_id' => '17'],
    		['id' => '751', 'city' => 'Rivera','department_id' => '41'],
    		['id' => '752', 'city' => 'Roberto Payán (San José)','department_id' => '52'],
    		['id' => '753', 'city' => 'Roldanillo','department_id' => '76'],
    		['id' => '754', 'city' => 'Roncesvalles','department_id' => '73'],
    		['id' => '755', 'city' => 'Rondón','department_id' => '15'],
    		['id' => '756', 'city' => 'Rosas','department_id' => '19'],
    		['id' => '757', 'city' => 'Rovira','department_id' => '73'],
    		['id' => '758', 'city' => 'Ráquira','department_id' => '15'],
    		['id' => '759', 'city' => 'Río Iró','department_id' => '27'],
    		['id' => '760', 'city' => 'Río Quito','department_id' => '27'],
    		['id' => '761', 'city' => 'Río Sucio','department_id' => '17'],
    		['id' => '762', 'city' => 'Río Viejo','department_id' => '13'],
    		['id' => '763', 'city' => 'Río de oro','department_id' => '20'],
    		['id' => '764', 'city' => 'Ríonegro','department_id' => '5'],
    		['id' => '765', 'city' => 'Ríosucio','department_id' => '27'],
    		['id' => '766', 'city' => 'Sabana de Torres','department_id' => '68'],
    		['id' => '767', 'city' => 'Sabanagrande','department_id' => '8'],
    		['id' => '768', 'city' => 'Sabanalarga','department_id' => '5'],
    		['id' => '769', 'city' => 'Sabanalarga','department_id' => '8'],
    		['id' => '770', 'city' => 'Sabanalarga','department_id' => '85'],
    		['id' => '771', 'city' => 'Sabanas de San Angel (SAN ANGEL)','department_id' => '47'],
    		['id' => '772', 'city' => 'Sabaneta','department_id' => '5'],
    		['id' => '773', 'city' => 'Saboyá','department_id' => '15'],
    		['id' => '774', 'city' => 'Sahagún','department_id' => '23'],
    		['id' => '775', 'city' => 'Saladoblanco','department_id' => '41'],
    		['id' => '776', 'city' => 'Salamina','department_id' => '17'],
    		['id' => '777', 'city' => 'Salamina','department_id' => '47'],
    		['id' => '778', 'city' => 'Salazar','department_id' => '54'],
    		['id' => '779', 'city' => 'Saldaña','department_id' => '73'],
    		['id' => '780', 'city' => 'Salento','department_id' => '63'],
    		['id' => '781', 'city' => 'Salgar','department_id' => '5'],
    		['id' => '782', 'city' => 'Samacá','department_id' => '15'],
    		['id' => '783', 'city' => 'Samaniego','department_id' => '52'],
    		['id' => '784', 'city' => 'Samaná','department_id' => '17'],
    		['id' => '785', 'city' => 'Sampués','department_id' => '70'],
    		['id' => '786', 'city' => 'San Agustín','department_id' => '41'],
    		['id' => '787', 'city' => 'San Alberto','department_id' => '20'],
    		['id' => '788', 'city' => 'San Andrés','department_id' => '68'],
    		['id' => '789', 'city' => 'San Andrés Sotavento','department_id' => '23'],
    		['id' => '790', 'city' => 'San Andrés de Cuerquía','department_id' => '5'],
    		['id' => '791', 'city' => 'San Antero','department_id' => '23'],
    		['id' => '792', 'city' => 'San Antonio','department_id' => '73'],
    		['id' => '793', 'city' => 'San Antonio de Tequendama','department_id' => '25'],
    		['id' => '794', 'city' => 'San Benito','department_id' => '68'],
    		['id' => '795', 'city' => 'San Benito Abad','department_id' => '70'],
    		['id' => '796', 'city' => 'San Bernardo','department_id' => '25'],
    		['id' => '797', 'city' => 'San Bernardo','department_id' => '52'],
    		['id' => '798', 'city' => 'San Bernardo del Viento','department_id' => '23'],
    		['id' => '799', 'city' => 'San Calixto','department_id' => '54'],
    		['id' => '800', 'city' => 'San Carlos','department_id' => '5'],
    		['id' => '801', 'city' => 'San Carlos','department_id' => '23'],
    		['id' => '802', 'city' => 'San Carlos de Guaroa','department_id' => '50'],
    		['id' => '803', 'city' => 'San Cayetano','department_id' => '25'],
    		['id' => '804', 'city' => 'San Cayetano','department_id' => '54'],
    		['id' => '805', 'city' => 'San Cristobal','department_id' => '13'],
    		['id' => '806', 'city' => 'San Diego','department_id' => '20'],
    		['id' => '807', 'city' => 'San Eduardo','department_id' => '15'],
    		['id' => '808', 'city' => 'San Estanislao','department_id' => '13'],
    		['id' => '809', 'city' => 'San Fernando','department_id' => '13'],
    		['id' => '810', 'city' => 'San Francisco','department_id' => '5'],
    		['id' => '811', 'city' => 'San Francisco','department_id' => '25'],
    		['id' => '812', 'city' => 'San Francisco','department_id' => '86'],
    		['id' => '813', 'city' => 'San Gíl','department_id' => '68'],
    		['id' => '814', 'city' => 'San Jacinto','department_id' => '13'],
    		['id' => '815', 'city' => 'San Jacinto del Cauca','department_id' => '13'],
    		['id' => '816', 'city' => 'San Jerónimo','department_id' => '5'],
    		['id' => '817', 'city' => 'San Joaquín','department_id' => '68'],
    		['id' => '818', 'city' => 'San José','department_id' => '17'],
    		['id' => '819', 'city' => 'San José de Miranda','department_id' => '68'],
    		['id' => '820', 'city' => 'San José de Montaña','department_id' => '5'],
    		['id' => '821', 'city' => 'San José de Pare','department_id' => '15'],
    		['id' => '822', 'city' => 'San José de Uré','department_id' => '23'],
    		['id' => '823', 'city' => 'San José del Fragua','department_id' => '18'],
    		['id' => '824', 'city' => 'San José del Guaviare','department_id' => '95'],
    		['id' => '825', 'city' => 'San José del Palmar','department_id' => '27'],
    		['id' => '826', 'city' => 'San Juan de Arama','department_id' => '50'],
    		['id' => '827', 'city' => 'San Juan de Betulia','department_id' => '70'],
    		['id' => '828', 'city' => 'San Juan de Nepomuceno','department_id' => '13'],
    		['id' => '829', 'city' => 'San Juan de Pasto','department_id' => '52'],
    		['id' => '830', 'city' => 'San Juan de Río Seco','department_id' => '25'],
    		['id' => '831', 'city' => 'San Juan de Urabá','department_id' => '5'],
    		['id' => '832', 'city' => 'San Juan del Cesar','department_id' => '44'],
    		['id' => '833', 'city' => 'San Juanito','department_id' => '50'],
    		['id' => '834', 'city' => 'San Lorenzo','department_id' => '52'],
    		['id' => '835', 'city' => 'San Luis','department_id' => '73'],
    		['id' => '836', 'city' => 'San Luís','department_id' => '5'],
    		['id' => '837', 'city' => 'San Luís de Gaceno','department_id' => '15'],
    		['id' => '838', 'city' => 'San Luís de Palenque','department_id' => '85'],
    		['id' => '839', 'city' => 'San Marcos','department_id' => '70'],
    		['id' => '840', 'city' => 'San Martín','department_id' => '20'],
    		['id' => '841', 'city' => 'San Martín','department_id' => '50'],
    		['id' => '842', 'city' => 'San Martín de Loba','department_id' => '13'],
    		['id' => '843', 'city' => 'San Mateo','department_id' => '15'],
    		['id' => '844', 'city' => 'San Miguel','department_id' => '68'],
    		['id' => '845', 'city' => 'San Miguel','department_id' => '86'],
    		['id' => '846', 'city' => 'San Miguel de Sema','department_id' => '15'],
    		['id' => '847', 'city' => 'San Onofre','department_id' => '70'],
    		['id' => '848', 'city' => 'San Pablo','department_id' => '13'],
    		['id' => '849', 'city' => 'San Pablo','department_id' => '52'],
    		['id' => '850', 'city' => 'San Pablo de Borbur','department_id' => '15'],
    		['id' => '851', 'city' => 'San Pedro','department_id' => '5'],
    		['id' => '852', 'city' => 'San Pedro','department_id' => '70'],
    		['id' => '853', 'city' => 'San Pedro','department_id' => '76'],
    		['id' => '854', 'city' => 'San Pedro de Cartago','department_id' => '52'],
    		['id' => '855', 'city' => 'San Pedro de Urabá','department_id' => '5'],
    		['id' => '856', 'city' => 'San Pelayo','department_id' => '23'],
    		['id' => '857', 'city' => 'San Rafael','department_id' => '5'],
    		['id' => '858', 'city' => 'San Roque','department_id' => '5'],
    		['id' => '859', 'city' => 'San Sebastián','department_id' => '19'],
    		['id' => '860', 'city' => 'San Sebastián de Buenavista','department_id' => '47'],
    		['id' => '861', 'city' => 'San Vicente','department_id' => '5'],
    		['id' => '862', 'city' => 'San Vicente del Caguán','department_id' => '18'],
    		['id' => '863', 'city' => 'San Vicente del Chucurí','department_id' => '68'],
    		['id' => '864', 'city' => 'San Zenón','department_id' => '47'],
    		['id' => '865', 'city' => 'Sandoná','department_id' => '52'],
    		['id' => '866', 'city' => 'Santa Ana','department_id' => '47'],
    		['id' => '867', 'city' => 'Santa Bárbara','department_id' => '5'],
    		['id' => '868', 'city' => 'Santa Bárbara','department_id' => '68'],
    		['id' => '869', 'city' => 'Santa Bárbara (Iscuandé)','department_id' => '52'],
    		['id' => '870', 'city' => 'Santa Bárbara de Pinto','department_id' => '47'],
    		['id' => '871', 'city' => 'Santa Catalina','department_id' => '13'],
    		['id' => '872', 'city' => 'Santa Fé de Antioquia','department_id' => '5'],
    		['id' => '873', 'city' => 'Santa Genoveva de Docorodó','department_id' => '27'],
    		['id' => '874', 'city' => 'Santa Helena del Opón','department_id' => '68'],
    		['id' => '875', 'city' => 'Santa Isabel','department_id' => '73'],
    		['id' => '876', 'city' => 'Santa Lucía','department_id' => '8'],
    		['id' => '877', 'city' => 'Santa Marta','department_id' => '47'],
    		['id' => '878', 'city' => 'Santa María','department_id' => '15'],
    		['id' => '879', 'city' => 'Santa María','department_id' => '41'],
    		['id' => '880', 'city' => 'Santa Rosa','department_id' => '13'],
    		['id' => '881', 'city' => 'Santa Rosa','department_id' => '19'],
    		['id' => '882', 'city' => 'Santa Rosa de Cabal','department_id' => '66'],
    		['id' => '883', 'city' => 'Santa Rosa de Osos','department_id' => '5'],
    		['id' => '884', 'city' => 'Santa Rosa de Viterbo','department_id' => '15'],
    		['id' => '885', 'city' => 'Santa Rosa del Sur','department_id' => '13'],
    		['id' => '886', 'city' => 'Santa Rosalía','department_id' => '99'],
    		['id' => '887', 'city' => 'Santa Sofía','department_id' => '15'],
    		['id' => '888', 'city' => 'Santana','department_id' => '15'],
    		['id' => '889', 'city' => 'Santander de Quilichao','department_id' => '19'],
    		['id' => '890', 'city' => 'Santiago','department_id' => '54'],
    		['id' => '891', 'city' => 'Santiago','department_id' => '86'],
    		['id' => '892', 'city' => 'Santo Domingo','department_id' => '5'],
    		['id' => '893', 'city' => 'Santo Tomás','department_id' => '8'],
    		['id' => '894', 'city' => 'Santuario','department_id' => '5'],
    		['id' => '895', 'city' => 'Santuario','department_id' => '66'],
    		['id' => '896', 'city' => 'Sapuyes','department_id' => '52'],
    		['id' => '897', 'city' => 'Saravena','department_id' => '81'],
    		['id' => '898', 'city' => 'Sardinata','department_id' => '54'],
    		['id' => '899', 'city' => 'Sasaima','department_id' => '25'],
    		['id' => '900', 'city' => 'Sativanorte','department_id' => '15'],
    		['id' => '901', 'city' => 'Sativasur','department_id' => '15'],
    		['id' => '902', 'city' => 'Segovia','department_id' => '5'],
    		['id' => '903', 'city' => 'Sesquilé','department_id' => '25'],
    		['id' => '904', 'city' => 'Sevilla','department_id' => '76'],
    		['id' => '905', 'city' => 'Siachoque','department_id' => '15'],
    		['id' => '906', 'city' => 'Sibaté','department_id' => '25'],
    		['id' => '907', 'city' => 'Sibundoy','department_id' => '86'],
    		['id' => '908', 'city' => 'Silos','department_id' => '54'],
    		['id' => '909', 'city' => 'Silvania','department_id' => '25'],
    		['id' => '910', 'city' => 'Silvia','department_id' => '19'],
    		['id' => '911', 'city' => 'Simacota','department_id' => '68'],
    		['id' => '912', 'city' => 'Simijaca','department_id' => '25'],
    		['id' => '913', 'city' => 'Simití','department_id' => '13'],
    		['id' => '914', 'city' => 'Sincelejo','department_id' => '70'],
    		['id' => '915', 'city' => 'Sincé','department_id' => '70'],
    		['id' => '916', 'city' => 'Sipí','department_id' => '27'],
    		['id' => '917', 'city' => 'Sitionuevo','department_id' => '47'],
    		['id' => '918', 'city' => 'Soacha','department_id' => '25'],
    		['id' => '919', 'city' => 'Soatá','department_id' => '15'],
    		['id' => '920', 'city' => 'Socha','department_id' => '15'],
    		['id' => '921', 'city' => 'Socorro','department_id' => '68'],
    		['id' => '922', 'city' => 'Socotá','department_id' => '15'],
    		['id' => '923', 'city' => 'Sogamoso','department_id' => '15'],
    		['id' => '924', 'city' => 'Solano','department_id' => '18'],
    		['id' => '925', 'city' => 'Soledad','department_id' => '8'],
    		['id' => '926', 'city' => 'Solita','department_id' => '18'],
    		['id' => '927', 'city' => 'Somondoco','department_id' => '15'],
    		['id' => '928', 'city' => 'Sonsón','department_id' => '5'],
    		['id' => '929', 'city' => 'Sopetrán','department_id' => '5'],
    		['id' => '930', 'city' => 'Soplaviento','department_id' => '13'],
    		['id' => '931', 'city' => 'Sopó','department_id' => '25'],
    		['id' => '932', 'city' => 'Sora','department_id' => '15'],
    		['id' => '933', 'city' => 'Soracá','department_id' => '15'],
    		['id' => '934', 'city' => 'Sotaquirá','department_id' => '15'],
    		['id' => '935', 'city' => 'Sotara (Paispamba)','department_id' => '19'],
    		['id' => '936', 'city' => 'Sotomayor (Los Andes)','department_id' => '52'],
    		['id' => '937', 'city' => 'Suaita','department_id' => '68'],
    		['id' => '938', 'city' => 'Suan','department_id' => '8'],
    		['id' => '939', 'city' => 'Suaza','department_id' => '41'],
    		['id' => '940', 'city' => 'Subachoque','department_id' => '25'],
    		['id' => '941', 'city' => 'Sucre','department_id' => '19'],
    		['id' => '942', 'city' => 'Sucre','department_id' => '68'],
    		['id' => '943', 'city' => 'Sucre','department_id' => '70'],
    		['id' => '944', 'city' => 'Suesca','department_id' => '25'],
    		['id' => '945', 'city' => 'Supatá','department_id' => '25'],
    		['id' => '946', 'city' => 'Supía','department_id' => '17'],
    		['id' => '947', 'city' => 'Suratá','department_id' => '68'],
    		['id' => '948', 'city' => 'Susa','department_id' => '25'],
    		['id' => '949', 'city' => 'Susacón','department_id' => '15'],
    		['id' => '950', 'city' => 'Sutamarchán','department_id' => '15'],
    		['id' => '951', 'city' => 'Sutatausa','department_id' => '25'],
    		['id' => '952', 'city' => 'Sutatenza','department_id' => '15'],
    		['id' => '953', 'city' => 'Suárez','department_id' => '19'],
    		['id' => '954', 'city' => 'Suárez','department_id' => '73'],
    		['id' => '955', 'city' => 'Sácama','department_id' => '85'],
    		['id' => '956', 'city' => 'Sáchica','department_id' => '15'],
    		['id' => '957', 'city' => 'Tabio','department_id' => '25'],
    		['id' => '958', 'city' => 'Tadó','department_id' => '27'],
    		['id' => '959', 'city' => 'Talaigua Nuevo','department_id' => '13'],
    		['id' => '960', 'city' => 'Tamalameque','department_id' => '20'],
    		['id' => '961', 'city' => 'Tame','department_id' => '81'],
    		['id' => '962', 'city' => 'Taminango','department_id' => '52'],
    		['id' => '963', 'city' => 'Tangua','department_id' => '52'],
    		['id' => '964', 'city' => 'Taraira','department_id' => '97'],
    		['id' => '965', 'city' => 'Tarazá','department_id' => '5'],
    		['id' => '966', 'city' => 'Tarqui','department_id' => '41'],
    		['id' => '967', 'city' => 'Tarso','department_id' => '5'],
    		['id' => '968', 'city' => 'Tasco','department_id' => '15'],
    		['id' => '969', 'city' => 'Tauramena','department_id' => '85'],
    		['id' => '970', 'city' => 'Tausa','department_id' => '25'],
    		['id' => '971', 'city' => 'Tello','department_id' => '41'],
    		['id' => '972', 'city' => 'Tena','department_id' => '25'],
    		['id' => '973', 'city' => 'Tenerife','department_id' => '47'],
    		['id' => '974', 'city' => 'Tenjo','department_id' => '25'],
    		['id' => '975', 'city' => 'Tenza','department_id' => '15'],
    		['id' => '976', 'city' => 'Teorama','department_id' => '54'],
    		['id' => '977', 'city' => 'Teruel','department_id' => '41'],
    		['id' => '978', 'city' => 'Tesalia','department_id' => '41'],
    		['id' => '979', 'city' => 'Tibacuy','department_id' => '25'],
    		['id' => '980', 'city' => 'Tibaná','department_id' => '15'],
    		['id' => '981', 'city' => 'Tibasosa','department_id' => '15'],
    		['id' => '982', 'city' => 'Tibirita','department_id' => '25'],
    		['id' => '983', 'city' => 'Tibú','department_id' => '54'],
    		['id' => '984', 'city' => 'Tierralta','department_id' => '23'],
    		['id' => '985', 'city' => 'Timaná','department_id' => '41'],
    		['id' => '986', 'city' => 'Timbiquí','department_id' => '19'],
    		['id' => '987', 'city' => 'Timbío','department_id' => '19'],
    		['id' => '988', 'city' => 'Tinjacá','department_id' => '15'],
    		['id' => '989', 'city' => 'Tipacoque','department_id' => '15'],
    		['id' => '990', 'city' => 'Tiquisio (Puerto Rico)','department_id' => '13'],
    		['id' => '991', 'city' => 'Titiribí','department_id' => '5'],
    		['id' => '992', 'city' => 'Toca','department_id' => '15'],
    		['id' => '993', 'city' => 'Tocaima','department_id' => '25'],
    		['id' => '994', 'city' => 'Tocancipá','department_id' => '25'],
    		['id' => '995', 'city' => 'Toguí','department_id' => '15'],
    		['id' => '996', 'city' => 'Toledo','department_id' => '5'],
    		['id' => '997', 'city' => 'Toledo','department_id' => '54'],
    		['id' => '998', 'city' => 'Tolú','department_id' => '70'],
    		['id' => '999', 'city' => 'Tolú Viejo','department_id' => '70'],
    		['id' => '1000', 'city' => 'Tona','department_id' => '68'],
    		['id' => '1001', 'city' => 'Topagá','department_id' => '15'],
    		['id' => '1002', 'city' => 'Topaipí','department_id' => '25'],
    		['id' => '1003', 'city' => 'Toribío','department_id' => '19'],
    		['id' => '1004', 'city' => 'Toro','department_id' => '76'],
    		['id' => '1005', 'city' => 'Tota','department_id' => '15'],
    		['id' => '1006', 'city' => 'Totoró','department_id' => '19'],
    		['id' => '1007', 'city' => 'Trinidad','department_id' => '85'],
    		['id' => '1008', 'city' => 'Trujillo','department_id' => '76'],
    		['id' => '1009', 'city' => 'Tubará','department_id' => '8'],
    		['id' => '1010', 'city' => 'Tuchín','department_id' => '23'],
    		['id' => '1011', 'city' => 'Tulúa','department_id' => '76'],
    		['id' => '1012', 'city' => 'Tumaco','department_id' => '52'],
    		['id' => '1013', 'city' => 'Tunja','department_id' => '15'],
    		['id' => '1014', 'city' => 'Tunungua','department_id' => '15'],
    		['id' => '1015', 'city' => 'Turbaco','department_id' => '13'],
    		['id' => '1016', 'city' => 'Turbaná','department_id' => '13'],
    		['id' => '1017', 'city' => 'Turbo','department_id' => '5'],
    		['id' => '1018', 'city' => 'Turmequé','department_id' => '15'],
    		['id' => '1019', 'city' => 'Tuta','department_id' => '15'],
    		['id' => '1020', 'city' => 'Tutasá','department_id' => '15'],
    		['id' => '1021', 'city' => 'Támara','department_id' => '85'],
    		['id' => '1022', 'city' => 'Támesis','department_id' => '5'],
    		['id' => '1023', 'city' => 'Túquerres','department_id' => '52'],
    		['id' => '1024', 'city' => 'Ubalá','department_id' => '25'],
    		['id' => '1025', 'city' => 'Ubaque','department_id' => '25'],
    		['id' => '1026', 'city' => 'Ubaté','department_id' => '25'],
    		['id' => '1027', 'city' => 'Ulloa','department_id' => '76'],
    		['id' => '1028', 'city' => 'Une','department_id' => '25'],
    		['id' => '1029', 'city' => 'Unguía','department_id' => '27'],
    		['id' => '1030', 'city' => 'Unión Panamericana (ÁNIMAS)','department_id' => '27'],
    		['id' => '1031', 'city' => 'Uramita','department_id' => '5'],
    		['id' => '1032', 'city' => 'Uribe','department_id' => '50'],
    		['id' => '1033', 'city' => 'Uribia','department_id' => '44'],
    		['id' => '1034', 'city' => 'Urrao','department_id' => '5'],
    		['id' => '1035', 'city' => 'Urumita','department_id' => '44'],
    		['id' => '1036', 'city' => 'Usiacuri','department_id' => '8'],
    		['id' => '1037', 'city' => 'Valdivia','department_id' => '5'],
    		['id' => '1038', 'city' => 'Valencia','department_id' => '23'],
    		['id' => '1039', 'city' => 'Valle de San José','department_id' => '68'],
    		['id' => '1040', 'city' => 'Valle de San Juan','department_id' => '73'],
    		['id' => '1041', 'city' => 'Valle del Guamuez','department_id' => '86'],
    		['id' => '1042', 'city' => 'Valledupar','department_id' => '20'],
    		['id' => '1043', 'city' => 'Valparaiso','department_id' => '5'],
    		['id' => '1044', 'city' => 'Valparaiso','department_id' => '18'],
    		['id' => '1045', 'city' => 'Vegachí','department_id' => '5'],
    		['id' => '1046', 'city' => 'Venadillo','department_id' => '73'],
    		['id' => '1047', 'city' => 'Venecia','department_id' => '5'],
    		['id' => '1048', 'city' => 'Venecia (Ospina Pérez)','department_id' => '25'],
    		['id' => '1049', 'city' => 'Ventaquemada','department_id' => '15'],
    		['id' => '1050', 'city' => 'Vergara','department_id' => '25'],
    		['id' => '1051', 'city' => 'Versalles','department_id' => '76'],
    		['id' => '1052', 'city' => 'Vetas','department_id' => '68'],
    		['id' => '1053', 'city' => 'Viani','department_id' => '25'],
    		['id' => '1054', 'city' => 'Vigía del Fuerte','department_id' => '5'],
    		['id' => '1055', 'city' => 'Vijes','department_id' => '76'],
    		['id' => '1056', 'city' => 'Villa Caro','department_id' => '54'],
    		['id' => '1057', 'city' => 'Villa Rica','department_id' => '19'],
    		['id' => '1058', 'city' => 'Villa de Leiva','department_id' => '15'],
    		['id' => '1059', 'city' => 'Villa del Rosario','department_id' => '54'],
    		['id' => '1060', 'city' => 'Villagarzón','department_id' => '86'],
    		['id' => '1061', 'city' => 'Villagómez','department_id' => '25'],
    		['id' => '1062', 'city' => 'Villahermosa','department_id' => '73'],
    		['id' => '1063', 'city' => 'Villamaría','department_id' => '17'],
    		['id' => '1064', 'city' => 'Villanueva','department_id' => '13'],
    		['id' => '1065', 'city' => 'Villanueva','department_id' => '44'],
    		['id' => '1066', 'city' => 'Villanueva','department_id' => '68'],
    		['id' => '1067', 'city' => 'Villanueva','department_id' => '85'],
    		['id' => '1068', 'city' => 'Villapinzón','department_id' => '25'],
    		['id' => '1069', 'city' => 'Villarrica','department_id' => '73'],
    		['id' => '1070', 'city' => 'Villavicencio','department_id' => '50'],
    		['id' => '1071', 'city' => 'Villavieja','department_id' => '41'],
    		['id' => '1072', 'city' => 'Villeta','department_id' => '25'],
    		['id' => '1073', 'city' => 'Viotá','department_id' => '25'],
    		['id' => '1074', 'city' => 'Viracachá','department_id' => '15'],
    		['id' => '1075', 'city' => 'Vista Hermosa','department_id' => '50'],
    		['id' => '1076', 'city' => 'Viterbo','department_id' => '17'],
    		['id' => '1077', 'city' => 'Vélez','department_id' => '68'],
    		['id' => '1078', 'city' => 'Yacopí','department_id' => '25'],
    		['id' => '1079', 'city' => 'Yacuanquer','department_id' => '52'],
    		['id' => '1080', 'city' => 'Yaguará','department_id' => '41'],
    		['id' => '1081', 'city' => 'Yalí','department_id' => '5'],
    		['id' => '1082', 'city' => 'Yarumal','department_id' => '5'],
    		['id' => '1083', 'city' => 'Yolombó','department_id' => '5'],
    		['id' => '1084', 'city' => 'Yondó (Casabe)','department_id' => '5'],
    		['id' => '1085', 'city' => 'Yopal','department_id' => '85'],
    		['id' => '1086', 'city' => 'Yotoco','department_id' => '76'],
    		['id' => '1087', 'city' => 'Yumbo','department_id' => '76'],
    		['id' => '1088', 'city' => 'Zambrano','department_id' => '13'],
    		['id' => '1089', 'city' => 'Zapatoca','department_id' => '68'],
    		['id' => '1090', 'city' => 'Zapayán (PUNTA DE PIEDRAS)','department_id' => '47'],
    		['id' => '1091', 'city' => 'Zaragoza','department_id' => '5'],
    		['id' => '1092', 'city' => 'Zarzal','department_id' => '76'],
    		['id' => '1093', 'city' => 'Zetaquirá','department_id' => '15'],
    		['id' => '1094', 'city' => 'Zipacón','department_id' => '25'],
    		['id' => '1095', 'city' => 'Zipaquirá','department_id' => '25'],
    		['id' => '1096', 'city' => 'Zona Bananera (PRADO - SEVILLA)','department_id' => '47'],
    		['id' => '1097', 'city' => 'Ábrego','department_id' => '54'],
    		['id' => '1098', 'city' => 'Íquira','department_id' => '41'],
    		['id' => '1099', 'city' => 'Úmbita','department_id' => '15'],
    		['id' => '1100', 'city' => 'Útica','department_id' => '25'],

    	]);
}
}
